delete from LOGIN
delete from PROFESORESCURSOS
delete from ASISTENCIAS
delete from CALIFICACIONES
delete from MATRICULAS
delete from PERSONAS
delete from CODIGOSPOSTALES
delete from CURSOS
delete from AULAS
delete from TIPOSUSUARIOS
delete from TIPOSCURSOS
delete from TIPOSAULAS