CREATE PROCEDURE PROC_AULAS_CargarAulas
	
AS
	SELECT AULAS.Codigo,
		   AULAS.Nombre,AULAS.Tipo,
		   TIPOSAULAS.Tipo AS TipoAula,
		   AULAS.Observaciones
	FROM AULAS
	LEFT JOIN TIPOSAULAS ON AULAS.Tipo=TIPOSAULAS.Codigo
	ORDER BY AULAS.Codigo
GO

	