CREATE PROCEDURE PROC_ASISTENCIAS_CargarAsistenciasAlumnos
       @CodigoCurso CHAR(7),
       @Fecha DATE
       
AS 
	SELECT 
		(PERSONAS.NOMBRE+' '+PERSONAS.APELLIDOS) AS NOMBRECOMPLETO,
		ISNULL(ASISTENCIAS.FECHA,@Fecha) AS FECHA,
		ISNULL(ASISTENCIAS.ASISTIO,'N') AS ASISTIO,
		MATRICULAS.CodigoMatricula
	FROM PERSONAS
		INNER JOIN MATRICULAS ON
		MATRICULAS.NifAlumno=PERSONAS.Nif
		LEFT JOIN ASISTENCIAS ON
		ASISTENCIAS.CodigoMatricula=MATRICULAS.CodigoMatricula AND ASISTENCIAS.FECHA=@Fecha
	WHERE MATRICULAS.CodigoCurso=@CodigoCurso
GO